// <auto-generated />
using System;
using System.Text.Json;
using Harmony.Resolver.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Harmony.Resolver.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ResolverDbContext))]
    partial class ResolverDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Harmony.Resolver.Api.Infrastructure.Persistence.Entities.BackupCandidateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("ContentLength")
                        .HasColumnType("bigint")
                        .HasColumnName("content_length");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("ETag")
                        .HasColumnType("text")
                        .HasColumnName("etag");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FingerprintA")
                        .HasColumnType("text")
                        .HasColumnName("fingerprint_a");

                    b.Property<string>("FingerprintB")
                        .HasColumnType("text")
                        .HasColumnName("fingerprint_b");

                    b.Property<string>("StagingObjectKey")
                        .HasColumnType("text")
                        .HasColumnName("staging_object_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("video_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("VideoId")
                        .IsUnique();

                    b.ToTable("resolver_backup_candidates", null, t =>
                        {
                            t.HasCheckConstraint("ck_resolver_backup_candidate_status", "status IN ('pending', 'uploading', 'verifying', 'ready', 'rejected')");
                        });
                });

            modelBuilder.Entity("Harmony.Resolver.Api.Infrastructure.Persistence.Entities.DiagnosticAuditEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<JsonDocument>("QuerySummary")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("query_summary");

                    b.Property<string>("SubjectHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("subject_hash");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tool_name");

                    b.HasKey("Id");

                    b.ToTable("resolver_diagnostic_audit", (string)null);
                });

            modelBuilder.Entity("Harmony.Resolver.Api.Infrastructure.Persistence.Entities.IngestionLeaseEntity", b =>
                {
                    b.Property<string>("VideoId")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("video_id");

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acquired_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("VideoId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_resolver_leases_expiry");

                    b.ToTable("resolver_ingestion_leases", null, t =>
                        {
                            t.HasCheckConstraint("ck_resolver_leases_expiry", "expires_at > acquired_at");
                        });
                });

            modelBuilder.Entity("Harmony.Resolver.Api.Infrastructure.Persistence.Entities.PlayEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Cache")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("cache");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("IdentityHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("identity_hash");

                    b.Property<DateTimeOffset>("PlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("played_at");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("video_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_resolver_play_events_played_at");

                    b.ToTable("resolver_play_events", (string)null);
                });

            modelBuilder.Entity("Harmony.Resolver.Api.Infrastructure.Persistence.Entities.TrackEntity", b =>
                {
                    b.Property<string>("VideoId")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("video_id");

                    b.Property<long?>("ContentLength")
                        .HasColumnType("bigint")
                        .HasColumnName("content_length");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ETag")
                        .HasColumnType("text")
                        .HasColumnName("etag");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("failure_code");

                    b.Property<string>("IngestionKind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("ingestion_kind");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_accessed_at");

                    b.Property<string>("ObjectKey")
                        .HasColumnType("text")
                        .HasColumnName("object_key");

                    b.Property<DateTimeOffset?>("RetryAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retry_after");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("VideoId");

                    b.HasIndex("UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_resolver_tracks_failures")
                        .HasFilter("status = 'failed'");

                    b.HasIndex("Priority", "CreatedAt")
                        .IsDescending(true, false)
                        .HasDatabaseName("ix_resolver_tracks_pending")
                        .HasFilter("status = 'ingesting'");

                    b.ToTable("resolver_tracks", null, t =>
                        {
                            t.HasCheckConstraint("ck_resolver_tracks_ready_object", "(status = 'ready') = (object_key IS NOT NULL)");

                            t.HasCheckConstraint("ck_resolver_tracks_status", "status IN ('ingesting', 'ready', 'failed')");
                        });
                });

            modelBuilder.Entity("Harmony.Resolver.Api.Infrastructure.Persistence.Entities.IngestionLeaseEntity", b =>
                {
                    b.HasOne("Harmony.Resolver.Api.Infrastructure.Persistence.Entities.TrackEntity", "Track")
                        .WithOne("Lease")
                        .HasForeignKey("Harmony.Resolver.Api.Infrastructure.Persistence.Entities.IngestionLeaseEntity", "VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Harmony.Resolver.Api.Infrastructure.Persistence.Entities.TrackEntity", b =>
                {
                    b.Navigation("Lease");
                });
#pragma warning restore 612, 618
        }
    }
}
