// <auto-generated />
using System;
using System.Text.Json;
using Harmony.Resolver.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Harmony.Resolver.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ResolverDbContext))]
    partial class ResolverDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Harmony.Resolver.Api.Infrastructure.Persistence.Entities.DiagnosticAuditEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<JsonDocument>("QuerySummary")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("query_summary");

                    b.Property<string>("SubjectHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("subject_hash");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tool_name");

                    b.HasKey("Id");

                    b.ToTable("resolver_diagnostic_audit", (string)null);
                });

            modelBuilder.Entity("Harmony.Resolver.Api.Infrastructure.Persistence.Entities.IngestionLeaseEntity", b =>
                {
                    b.Property<string>("VideoId")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("video_id");

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acquired_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("VideoId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_resolver_leases_expiry");

                    b.ToTable("resolver_ingestion_leases", null, t =>
                        {
                            t.HasCheckConstraint("ck_resolver_leases_expiry", "expires_at > acquired_at");
                        });
                });

            modelBuilder.Entity("Harmony.Resolver.Api.Infrastructure.Persistence.Entities.TrackEntity", b =>
                {
                    b.Property<string>("VideoId")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("video_id");

                    b.Property<long?>("ContentLength")
                        .HasColumnType("bigint")
                        .HasColumnName("content_length");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ETag")
                        .HasColumnType("text")
                        .HasColumnName("etag");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("failure_code");

                    b.Property<DateTimeOffset>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_accessed_at");

                    b.Property<string>("ObjectKey")
                        .HasColumnType("text")
                        .HasColumnName("object_key");

                    b.Property<DateTimeOffset?>("RetryAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retry_after");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("VideoId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_resolver_tracks_expiry")
                        .HasFilter("status = 'ready'");

                    b.HasIndex("UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_resolver_tracks_failures")
                        .HasFilter("status = 'failed'");

                    b.ToTable("resolver_tracks", null, t =>
                        {
                            t.HasCheckConstraint("ck_resolver_tracks_ready_object", "(status = 'ready') = (object_key IS NOT NULL)");

                            t.HasCheckConstraint("ck_resolver_tracks_status", "status IN ('ingesting', 'ready', 'failed')");
                        });
                });

            modelBuilder.Entity("Harmony.Resolver.Api.Infrastructure.Persistence.Entities.IngestionLeaseEntity", b =>
                {
                    b.HasOne("Harmony.Resolver.Api.Infrastructure.Persistence.Entities.TrackEntity", "Track")
                        .WithOne("Lease")
                        .HasForeignKey("Harmony.Resolver.Api.Infrastructure.Persistence.Entities.IngestionLeaseEntity", "VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Harmony.Resolver.Api.Infrastructure.Persistence.Entities.TrackEntity", b =>
                {
                    b.Navigation("Lease");
                });
#pragma warning restore 612, 618
        }
    }
}
