namespace Harmony.Resolver.Downloader;

/// <summary>
/// Configuration for the headless downloader agent, read from environment variables (optionally via a
/// local <c>.env</c> file or user-secrets). Auth0 is optional: when <c>AUTH0_DOMAIN</c> is unset the
/// agent sends no bearer token, which only works against a Development resolver whose worker endpoints
/// run open — production resolvers require a <c>tracks:ingest</c> M2M token.
/// </summary>
public sealed class DownloaderOptions
{
    public required string ResolverBaseUrl { get; init; }
    public string? Auth0Domain { get; init; }
    public string? Auth0ClientId { get; init; }
    public string? Auth0ClientSecret { get; init; }
    public string Auth0Audience { get; init; } = "https://harmony-resolver";
    public int PollSeconds { get; init; } = 5;
    public int MaxParallel { get; init; } = 1;
    public int MaxDurationMinutes { get; init; } = 9;
    public string YtDlpPath { get; init; } = "yt-dlp";
    public int DownloadTimeoutSeconds { get; init; } = 300;

    /// <summary>AMQPS connection to the resolver's RabbitMQ, e.g. <c>amqps://user:pass@host:5671/</c>. When
    /// unset the agent falls back to the fixed-interval claim poll.</summary>
    public string? RabbitMqUri { get; init; }
    public string RabbitMqQueue { get; init; } = "harmony.ingest.jobs";
    /// <summary>
    /// Optional SHA-256 fingerprint of the expected RabbitMQ server certificate. Required when the
    /// broker uses the self-signed certificate generated by the VPS bootstrap; leave unset for a
    /// certificate chaining to the host's normal trusted roots.
    /// </summary>
    public string? RabbitMqCertificateSha256 { get; init; }

    public bool Auth0Enabled => !string.IsNullOrWhiteSpace(Auth0Domain);
    public bool RabbitMqEnabled => !string.IsNullOrWhiteSpace(RabbitMqUri);

    public static DownloaderOptions FromEnvironment()
    {
        return new DownloaderOptions
        {
            ResolverBaseUrl = Require("RESOLVER_BASE_URL").TrimEnd('/') + "/",
            Auth0Domain = Environment.GetEnvironmentVariable("AUTH0_DOMAIN"),
            Auth0ClientId = Environment.GetEnvironmentVariable("AUTH0_CLIENT_ID"),
            Auth0ClientSecret = Environment.GetEnvironmentVariable("AUTH0_CLIENT_SECRET"),
            Auth0Audience = Environment.GetEnvironmentVariable("AUTH0_AUDIENCE") ?? "https://harmony-resolver",
            PollSeconds = ParseInt("DOWNLOADER_POLL_SECONDS", 5),
            MaxParallel = Math.Max(1, ParseInt("DOWNLOADER_MAX_PARALLEL", 1)),
            MaxDurationMinutes = ParseInt("DOWNLOADER_MAX_DURATION_MINUTES", 9),
            YtDlpPath = Environment.GetEnvironmentVariable("YTDLP_PATH") ?? "yt-dlp",
            DownloadTimeoutSeconds = ParseInt("DOWNLOAD_TIMEOUT_SECONDS", 300),
            RabbitMqUri = Environment.GetEnvironmentVariable("RABBITMQ_URI"),
            RabbitMqQueue = Environment.GetEnvironmentVariable("RABBITMQ_QUEUE") ?? "harmony.ingest.jobs",
            RabbitMqCertificateSha256 = Environment.GetEnvironmentVariable("RABBITMQ_CERT_SHA256")
        };
    }

    private static string Require(string name) => Environment.GetEnvironmentVariable(name)
        ?? throw new InvalidOperationException($"{name} is required.");

    private static int ParseInt(string name, int fallback) =>
        int.TryParse(Environment.GetEnvironmentVariable(name), out var value) && value > 0 ? value : fallback;
}
